# Generated by Django 5.2.9 on 2025-12-14 19:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160)),
                ('relationship', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=30)),
                ('id_document_number', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_pickups', to='core.child')),
            ],
            options={
                'ordering': ['-is_active', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('expected', 'Expected'), ('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half-day')], default='expected', max_length=10)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('absence_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.child')),
            ],
            options={
                'ordering': ['-attendance_date', 'child__last_name', 'child__first_name'],
                'indexes': [models.Index(fields=['attendance_date', 'status'], name='core_attend_attenda_97119f_idx')],
                'constraints': [models.UniqueConstraint(fields=('child', 'attendance_date'), name='uniq_attendance_child_date')],
            },
        ),
    ]
