# Generated by Django 5.2.9 on 2025-12-14 20:22

import core.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feetype_childfee_invoice_invoiceitem_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_month', models.CharField(default=core.models.current_billing_month, max_length=7, validators=[core.models._validate_billing_month])),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_billing', to='core.child')),
            ],
            options={
                'ordering': ['-billing_month', 'child__last_name', 'child__first_name'],
                'indexes': [models.Index(fields=['billing_month', 'status'], name='core_monthl_billing_4beb91_idx')],
                'constraints': [models.UniqueConstraint(fields=('child', 'billing_month'), name='uniq_monthly_billing_child_month')],
            },
        ),
    ]
