# Generated by Django 5.2.9 on 2025-12-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_monthlybilling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='fee_type',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='child',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='child',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='original_payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='received_by',
        ),
        migrations.DeleteModel(
            name='ChildFee',
        ),
        migrations.DeleteModel(
            name='FeeType',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
